-- CreateTable
CREATE TABLE "CommunicationSettings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "emailEnabled" BOOLEAN NOT NULL DEFAULT false,
    "emailProvider" TEXT NOT NULL DEFAULT 'smtp',
    "emailFromName" TEXT NOT NULL DEFAULT '',
    "emailFromAddress" TEXT NOT NULL DEFAULT '',
    "emailSmtpHost" TEXT NOT NULL DEFAULT '',
    "emailSmtpPort" INTEGER NOT NULL DEFAULT 587,
    "emailSmtpUser" TEXT NOT NULL DEFAULT '',
    "emailSmtpSecure" BOOLEAN NOT NULL DEFAULT true,
    "emailSmtpPassword" TEXT,
    "emailApiKey" TEXT,
    "whatsappEnabled" BOOLEAN NOT NULL DEFAULT false,
    "whatsappProvider" TEXT NOT NULL DEFAULT 'meta',
    "whatsappPhoneNumberId" TEXT NOT NULL DEFAULT '',
    "whatsappBusinessAccountId" TEXT NOT NULL DEFAULT '',
    "whatsappAccessToken" TEXT,
    "whatsappTwilioAccountSid" TEXT NOT NULL DEFAULT '',
    "whatsappTwilioAuthToken" TEXT,
    "whatsappTwilioNumber" TEXT NOT NULL DEFAULT '',
    "smsEnabled" BOOLEAN NOT NULL DEFAULT false,
    "smsProvider" TEXT NOT NULL DEFAULT 'twilio',
    "smsFromNumber" TEXT NOT NULL DEFAULT '',
    "smsTwilioAccountSid" TEXT NOT NULL DEFAULT '',
    "smsTwilioAuthToken" TEXT,
    "smsVonageApiKey" TEXT NOT NULL DEFAULT '',
    "smsVonageApiSecret" TEXT,
    "smsAwsAccessKey" TEXT NOT NULL DEFAULT '',
    "smsAwsSecretKey" TEXT,
    "smsAwsRegion" TEXT NOT NULL DEFAULT '',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
