CREATE TABLE "SystemDesignConfig" (
  "id" SERIAL NOT NULL,
  "colorPrimary" TEXT,
  "colorPrimaryHover" TEXT,
  "colorPrimaryLight" TEXT,
  "colorAccent" TEXT,
  "colorBackground" TEXT,
  "colorSurface" TEXT,
  "colorText" TEXT,
  "colorTextMuted" TEXT,
  "colorBorder" TEXT,
  "colorSuccess" TEXT,
  "colorError" TEXT,
  "fontFamily" TEXT,
  "borderRadius" INTEGER,
  "logoUrl" TEXT,
  "faviconUrl" TEXT,
  "tagline" TEXT,
  "defaultCurrency" TEXT,
  "defaultLocale" TEXT,
  "textDirection" TEXT,
  "enabledLocales" TEXT,
  "enabledCurrencies" TEXT,
  "heroStyle" TEXT,
  "heroImageMode" TEXT,
  "heroCarouselInterval" INTEGER,
  "searchResultsImageUrl" TEXT,
  "searchResultsImageMode" TEXT,
  "searchResultsCarouselInterval" INTEGER,
  "searchSidebarPosition" TEXT,
  "propertyListLayout" TEXT,
  "roomRatesDefaultExpanded" BOOLEAN,
  "roomSearchLayout" TEXT,
  "infantMaxAge" INTEGER,
  "childMaxAge" INTEGER,
  "onlinePaymentEnabled" BOOLEAN,
  "payAtHotelEnabled" BOOLEAN,
  "payAtHotelCardGuaranteeRequired" BOOLEAN,
  "aiLayoutDefault" BOOLEAN,
  "searchAiLayoutDefault" BOOLEAN,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SystemDesignConfig_pkey" PRIMARY KEY ("id")
);
