import type { FastifyInstance } from 'fastify'
import { prisma } from '../db/client.js'
import { verifyScrapeToken } from './onboarding-admin.route.js'

export async function onboardingScrapeRoutes(app: FastifyInstance) {
  // GET /hotel-onboarding/bm.js — the actual extraction script, served to the loader bookmarklet
  // Tiny bookmark stores only the fetch() call; actual code lives here (no length limits, updatable without re-drag)
  app.get('/hotel-onboarding/bm.js', async (request, reply) => {
    reply.header('Access-Control-Allow-Origin', '*')
    reply.header('Content-Type', 'application/javascript')
    // Determine API base from the request host (works for both dev and prod)
    const proto = (request.headers['x-forwarded-proto'] as string) ?? 'http'
    const host = (request.headers['x-forwarded-host'] as string) ?? request.headers.host ?? 'localhost:3000'
    const base = `${proto}://${host}`
    const script = buildBmScript(base)
    return reply.send(script)
  })

  // CORS preflight — bookmarklet runs on third-party domain (secure-hotel-booking.com)
  app.options('/hotel-onboarding/scrape-submit', async (_request, reply) => {
    return reply
      .header('Access-Control-Allow-Origin', '*')
      .header('Access-Control-Allow-Methods', 'POST, OPTIONS')
      .header('Access-Control-Allow-Headers', 'Content-Type')
      .code(204).send()
  })

  // POST /hotel-onboarding/scrape-submit
  // Called by the browser bookmarklet from the D-Edge booking page.
  // Auth: one-time token generated by the admin panel (no cookie needed).
  app.post<{
    Body: {
      token: string
      rooms: Array<{
        name: string; description?: string; images: string[]; amenities?: string[]
        size?: string; maxOccupancy?: string
        ratePlans?: Array<{ name: string; board?: string; cancellation?: string; price?: string; details?: string }>
      }>
      boardTypes?: string[]
      cancellationPolicies?: string[]
      url?: string
    }
  }>('/hotel-onboarding/scrape-submit', async (request, reply) => {
    reply.header('Access-Control-Allow-Origin', '*')

    const { token, rooms, boardTypes, cancellationPolicies, url } = request.body ?? {}
    if (!token || !Array.isArray(rooms)) {
      return reply.code(400).send({ ok: false, error: 'token and rooms required' })
    }

    // Validate token (stateless HMAC — no store needed, survives API restarts)
    const invitationId = verifyScrapeToken(token)
    if (!invitationId) return reply.code(401).send({ ok: false, error: 'Invalid or expired token' })

    // Merge rooms into existing harvestedData (preserves hotel info already harvested)
    const inv = await prisma.onboardingInvitation.findUnique({
      where: { id: invitationId },
      select: { harvestedData: true },
    })
    const existing = (inv?.harvestedData ?? {}) as Record<string, unknown>
    // Deduplicate by name — bookmarklet may match rate-plan rows nested inside room cards
    const seen = new Set<string>()
    const mergedRooms = rooms
      .filter(r => { const k = (r.name ?? '').trim().toLowerCase(); if (!k || seen.has(k)) return false; seen.add(k); return true })
      .map(r => ({
        name: r.name ?? '',
        description: r.description ?? '',
        images: r.images ?? [],
        amenities: r.amenities ?? [],
        bedConfiguration: (r as any).bedConfiguration ?? null,
        supportedOccupancies: [],
        maxAdults: null, maxOccupancy: null, maxChildren: null, maxInfants: null,
        baseOccupancy: null, baseAdults: null, baseChildren: null, baseInfants: null,
        adultsAgeFrom: null, childrenAgeFrom: null, childrenAgeTo: null, infantsAgeTo: null,
      }))

    // Strip hg_token from the saved URL so it doesn't pollute future requests
    let cleanUrl: string | undefined
    if (url) {
      try {
        const u = new URL(url)
        u.searchParams.delete('hg_token')
        cleanUrl = u.toString()
      } catch { cleanUrl = url }
    }

    // Build discoveredRatePlanTypes (schema: boardCode, boardCodeRawName, hasRefundable, hasNonRefundable)
    const allRatePlans = rooms.flatMap(r => r.ratePlans ?? [])
    const detectBoardCode = (text: string) =>
      /breakfast|bb\b/i.test(text) ? 'BB'
      : /half.?board|\bhb\b|demi/i.test(text) ? 'HB'
      : /full.?board|\bfb\b/i.test(text) ? 'FB'
      : /all.?incl|\bai\b/i.test(text) ? 'AI' : 'RO'

    // Group rate plans by boardCode — one entry per board type
    const boardMap = new Map<string, { raw: string; refund: boolean; nonRefund: boolean }>()
    for (const rp of allRatePlans) {
      const combined = [rp.name, rp.board, rp.cancellation, rp.details].filter(Boolean).join(' ')
      const bc = detectBoardCode(combined)
      const existing_entry = boardMap.get(bc)
      const isRefundable = /refund|flexible|free cancel/i.test(combined)
      const isNonRefundable = /non.?refund|no cancel|non remb/i.test(combined)
      if (!existing_entry) {
        boardMap.set(bc, { raw: rp.board ?? rp.name ?? bc, refund: isRefundable, nonRefund: isNonRefundable })
      } else {
        boardMap.set(bc, { ...existing_entry, refund: existing_entry.refund || isRefundable, nonRefund: existing_entry.nonRefund || isNonRefundable })
      }
    }
    const discoveredRatePlanTypes = boardMap.size
      ? Array.from(boardMap.entries()).map(([bc, v]) => ({
          boardCode: bc as 'RO' | 'BB' | 'HB' | 'FB' | 'AI',
          boardCodeRawName: v.raw,
          hasRefundable: v.refund,
          hasNonRefundable: v.nonRefund,
        }))
      : (existing['discoveredRatePlanTypes'] as unknown[] ?? [])

    // Build cancellation policies from scraped texts
    const cancelTexts = [...new Set([...(cancellationPolicies ?? []), ...allRatePlans.map(p => p.cancellation).filter((t): t is string => !!t)])]
    const scrapedPolicies = cancelTexts.map(text => ({
      name: text,
      type: /free|refund|flexible/i.test(text) ? 'flexible' : 'non_refundable',
      text,
    }))

    // Merge with any rooms already saved from previous tab submissions (same token used across tabs)
    const existingRooms = Array.isArray(existing['rooms']) ? existing['rooms'] as Record<string,unknown>[] : []
    const existingByName = new Map(existingRooms.map(r => [String(r['name'] ?? '').toLowerCase(), r]))
    for (const r of mergedRooms) {
      const key = r.name.toLowerCase()
      const prev = existingByName.get(key)
      if (!prev) { existingByName.set(key, r); continue }
      // Merge: prefer non-null / longer values from either submission
      const merged: Record<string,unknown> = { ...prev }
      for (const [k, v] of Object.entries(r)) {
        const pv = prev[k]
        if (v && (!pv || (Array.isArray(v) && Array.isArray(pv) && v.length > pv.length) || (typeof v === 'string' && typeof pv === 'string' && v.length > pv.length))) {
          merged[k] = v
        }
      }
      existingByName.set(key, merged)
    }
    const finalRooms = Array.from(existingByName.values())

    // Merge rate plan types with existing ones
    const existingRatePlans = Array.isArray(existing['discoveredRatePlanTypes'])
      ? existing['discoveredRatePlanTypes'] as Record<string,unknown>[]
      : []
    const mergedRatePlanMap = new Map(existingRatePlans.map(r => [String(r['boardCode']), r]))
    for (const rp of discoveredRatePlanTypes as Record<string,unknown>[]) {
      mergedRatePlanMap.set(String(rp['boardCode']), rp)
    }

    await prisma.onboardingInvitation.update({
      where: { id: invitationId },
      data: {
        harvestedData: {
          ...existing,
          rooms: finalRooms,
          discoveredRatePlanTypes: Array.from(mergedRatePlanMap.values()),
          ...(scrapedPolicies.length ? { policies: scrapedPolicies } : {}),
          ...(boardTypes?.length ? { boardTypes } : {}),
        },
        harvestStatus: 'completed',
        harvestCompletedAt: new Date(),
        ...(cleanUrl ? { ibeUrl: cleanUrl } : {}),
      },
    })

    return reply.send({ ok: true, roomsFound: rooms.length })
  })
}

function buildBmScript(base: string): string {
  // 3 patterns: 2A+0C, 1A+1C (finds family/child rooms), 3A+0C (larger rooms)
  return `(async function(){
function toast(m,ok,dur){var d=document.createElement('div');d.style.cssText='position:fixed;top:20px;right:20px;z-index:2147483647;background:'+(ok?'rgb(21,128,61)':'rgb(30,41,59)')+';color:white;padding:14px 18px;border-radius:8px;font-size:14px;font-family:sans-serif;box-shadow:0 4px 20px rgba(0,0,0,.5);max-width:340px;line-height:1.5;';d.textContent=m;document.body.appendChild(d);setTimeout(function(){d.remove();},dur||(ok?6000:4000));return d;}
var token=new URLSearchParams(location.search).get('hg_token');
if(!token){toast('Open this page using the HG Admin button');return;}
function tx(el){return el?(el.textContent||'').replace(/\\s+/g,' ').trim():'';}
function gi(el){return[].slice.call(el.querySelectorAll('img')).map(function(i){return i.src||i.getAttribute('data-src')||'';}).filter(function(s){return s.indexOf('https')===0;}).slice(0,6);}
var cards=document.querySelectorAll('[class*=room-card],[class*=RoomCard],[class*=accommodation-card],[class*=room-item]');
if(!cards.length){toast('Rooms not visible yet - wait for page to load');return;}
var rooms=[],bds={},cxs={};
// Collect leaf-text nodes from a card to extract structured values by pattern (works without knowing class names)
function leafTexts(c){return[].slice.call(c.querySelectorAll('span,li,em,small,div')).filter(function(el){return!el.children.length;}).map(function(el){return tx(el);}).filter(function(s){return s&&s.length>0&&s.length<80;});}
[].forEach.call(cards,function(c){
  var n=tx(c.querySelector('h2,h3,h4'));
  if(!n||n.length>200)return;
  var desc=tx(c.querySelector('[class*=description],[class*=detail],[class*=desc],[class*=summary]')).slice(0,400);
  var ltx=leafTexts(c);
  var occ=ltx.filter(function(s){return/\d+\s*(max|adult|person|guest|pax)/i.test(s);}).join(' / ');
  var sz=ltx.filter(function(s){return/\d+\s*m[\xb2²]|\d+\s*sq\s*m|\d+\s*sqft|\d+\s*ft/i.test(s);}).join(' / ');
  var bedConf=ltx.filter(function(s){return/\b(bed|twin|double|king|queen|sofa\s*bed|bunk|futon|single|matrimonial)/i.test(s)&&s.length<60;}).join(', ');
  var ams=[].slice.call(c.querySelectorAll('[class*=amenity],[class*=feature],[class*=facil],[class*=service]')).map(function(a){return tx(a);}).filter(function(s){return s&&s.length>1&&s.length<60;}).slice(0,15);
  var plans=[];
  var rateEls=c.querySelectorAll('[class*=rate],[class*=offer],[class*=package],[class*=plan],[class*=Price]');
  if(!rateEls.length){var next=c.nextElementSibling;while(next&&!next.matches('[class*=room],[class*=Room]')){var sub=next.querySelectorAll('[class*=rate],[class*=price],[class*=offer]');if(sub.length){rateEls=sub;break;}next=next.nextElementSibling;}}
  [].forEach.call(rateEls,function(r){
    var pn=tx(r.querySelector('h3,h4,h5,[class*=name],[class*=title]'));
    if(!pn||pn.length<2||pn.length>150)return;
    var price=tx(r.querySelector('[class*=price],[class*=amount],[class*=total],[class*=cost]'));
    var details=tx(r).replace(/\\s+/g,' ');
    var cancel='';var board='';
    if(/free cancel|refund/i.test(details))cancel=details.split('.')[0].trim().slice(0,120);
    if(/room only|breakfast|half board|full board|all incl/i.test(details))board=details.slice(0,60);
    if(cancel)cxs[cancel]=1;if(board)bds[board]=1;
    plans.push({name:pn,board:board,cancellation:cancel,price:price,details:details.slice(0,200)});
  });
  rooms.push({name:n,description:desc,images:gi(c),amenities:ams,size:sz,maxOccupancy:occ,bedConfiguration:bedConf,ratePlans:plans});
});
if(!rooms.length){toast('No rooms visible yet - wait for the page to fully load, then try again');return;}
// Submit current page capture — server merges with any previous clicks (token valid 24h)
toast('Saving '+rooms.length+' room(s) from this search...');
fetch('${base}/api/v1/hotel-onboarding/scrape-submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:token,rooms:finalRooms,boardTypes:Object.keys(bds),cancellationPolicies:Object.keys(cxs),url:location.href})}).then(function(r){return r.json();}).then(function(d){d.ok?toast(d.roomsFound+' room(s) saved. Change search (dates/guests) and click again for more patterns.',true,9000):toast('Error: '+(d.error||'unknown'));}).catch(function(){toast('Network error - check connection');});
})();`
}
