ALTER TABLE "HotelConfig" ADD COLUMN IF NOT EXISTS "showNameOnHeader" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "HotelConfig" ADD COLUMN IF NOT EXISTS "showLogoOnHeader" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "OrgDesignDefaults" ADD COLUMN IF NOT EXISTS "showNameOnHeader" BOOLEAN;
ALTER TABLE "OrgDesignDefaults" ADD COLUMN IF NOT EXISTS "showLogoOnHeader" BOOLEAN;
