interface CurrencyMeta { name: string; symbol: string }

const CURRENCIES: Record<string, CurrencyMeta> = {
  AED: { name: 'UAE Dirham',                   symbol: 'د.إ'  },
  AFN: { name: 'Afghan Afghani',               symbol: '؋'    },
  ALL: { name: 'Albanian Lek',                 symbol: 'L'    },
  AMD: { name: 'Armenian Dram',                symbol: '֏'    },
  ANG: { name: 'Antillean Guilder',            symbol: 'ƒ'    },
  AOA: { name: 'Angolan Kwanza',               symbol: 'Kz'   },
  ARS: { name: 'Argentine Peso',               symbol: '$'    },
  AUD: { name: 'Australian Dollar',            symbol: 'A$'   },
  AZN: { name: 'Azerbaijani Manat',            symbol: '₼'    },
  BAM: { name: 'Bosnia-Herzegovina Mark',      symbol: 'KM'   },
  BBD: { name: 'Barbadian Dollar',             symbol: 'Bds$' },
  BDT: { name: 'Bangladeshi Taka',             symbol: '৳'    },
  BGN: { name: 'Bulgarian Lev',                symbol: 'лв'   },
  BHD: { name: 'Bahraini Dinar',               symbol: 'BD'   },
  BIF: { name: 'Burundian Franc',              symbol: 'Fr'   },
  BMD: { name: 'Bermudian Dollar',             symbol: '$'    },
  BND: { name: 'Brunei Dollar',                symbol: 'B$'   },
  BOB: { name: 'Bolivian Boliviano',           symbol: 'Bs.'  },
  BRL: { name: 'Brazilian Real',               symbol: 'R$'   },
  BSD: { name: 'Bahamian Dollar',              symbol: 'B$'   },
  BTN: { name: 'Bhutanese Ngultrum',           symbol: 'Nu'   },
  BWP: { name: 'Botswanan Pula',               symbol: 'P'    },
  BYN: { name: 'Belarusian Ruble',             symbol: 'Br'   },
  BZD: { name: 'Belize Dollar',                symbol: 'BZ$'  },
  CAD: { name: 'Canadian Dollar',              symbol: 'C$'   },
  CDF: { name: 'Congolese Franc',              symbol: 'Fr'   },
  CHF: { name: 'Swiss Franc',                  symbol: 'Fr'   },
  CLP: { name: 'Chilean Peso',                 symbol: '$'    },
  CNY: { name: 'Chinese Yuan',                 symbol: '¥'    },
  COP: { name: 'Colombian Peso',               symbol: '$'    },
  CRC: { name: 'Costa Rican Colón',            symbol: '₡'    },
  CUP: { name: 'Cuban Peso',                   symbol: '$'    },
  CVE: { name: 'Cape Verdean Escudo',          symbol: '$'    },
  CZK: { name: 'Czech Koruna',                 symbol: 'Kč'   },
  DJF: { name: 'Djiboutian Franc',             symbol: 'Fr'   },
  DKK: { name: 'Danish Krone',                 symbol: 'kr'   },
  DOP: { name: 'Dominican Peso',               symbol: '$'    },
  DZD: { name: 'Algerian Dinar',               symbol: 'دج'   },
  EGP: { name: 'Egyptian Pound',               symbol: '£'    },
  ERN: { name: 'Eritrean Nakfa',               symbol: 'Nfk'  },
  ETB: { name: 'Ethiopian Birr',               symbol: 'Br'   },
  EUR: { name: 'Euro',                         symbol: '€'    },
  FJD: { name: 'Fijian Dollar',                symbol: 'FJ$'  },
  FKP: { name: 'Falkland Islands Pound',       symbol: '£'    },
  GBP: { name: 'Pound Sterling',               symbol: '£'    },
  GEL: { name: 'Georgian Lari',                symbol: '₾'    },
  GHS: { name: 'Ghanaian Cedi',                symbol: '₵'    },
  GIP: { name: 'Gibraltar Pound',              symbol: '£'    },
  GMD: { name: 'Gambian Dalasi',               symbol: 'D'    },
  GNF: { name: 'Guinean Franc',                symbol: 'Fr'   },
  GTQ: { name: 'Guatemalan Quetzal',           symbol: 'Q'    },
  GYD: { name: 'Guyanaese Dollar',             symbol: 'G$'   },
  HKD: { name: 'Hong Kong Dollar',             symbol: 'HK$'  },
  HNL: { name: 'Honduran Lempira',             symbol: 'L'    },
  HRK: { name: 'Croatian Kuna',                symbol: 'kn'   },
  HTG: { name: 'Haitian Gourde',               symbol: 'G'    },
  HUF: { name: 'Hungarian Forint',             symbol: 'Ft'   },
  IDR: { name: 'Indonesian Rupiah',            symbol: 'Rp'   },
  ILS: { name: 'Israeli Shekel',               symbol: '₪'    },
  INR: { name: 'Indian Rupee',                 symbol: '₹'    },
  IQD: { name: 'Iraqi Dinar',                  symbol: 'ع.د'  },
  IRR: { name: 'Iranian Rial',                 symbol: '﷼'    },
  ISK: { name: 'Icelandic Króna',              symbol: 'kr'   },
  JMD: { name: 'Jamaican Dollar',              symbol: 'J$'   },
  JOD: { name: 'Jordanian Dinar',              symbol: 'JD'   },
  JPY: { name: 'Japanese Yen',                 symbol: '¥'    },
  KES: { name: 'Kenyan Shilling',              symbol: 'KSh'  },
  KGS: { name: 'Kyrgystani Som',               symbol: 'лв'   },
  KHR: { name: 'Cambodian Riel',               symbol: '៛'    },
  KMF: { name: 'Comorian Franc',               symbol: 'Fr'   },
  KRW: { name: 'South Korean Won',             symbol: '₩'    },
  KWD: { name: 'Kuwaiti Dinar',                symbol: 'KD'   },
  KYD: { name: 'Cayman Islands Dollar',        symbol: 'KY$'  },
  KZT: { name: 'Kazakhstani Tenge',            symbol: '₸'    },
  LAK: { name: 'Laotian Kip',                  symbol: '₭'    },
  LBP: { name: 'Lebanese Pound',               symbol: 'ل.ل'  },
  LKR: { name: 'Sri Lankan Rupee',             symbol: '₨'    },
  LRD: { name: 'Liberian Dollar',              symbol: 'L$'   },
  LSL: { name: 'Lesotho Loti',                 symbol: 'L'    },
  LYD: { name: 'Libyan Dinar',                 symbol: 'ل.د'  },
  MAD: { name: 'Moroccan Dirham',              symbol: 'د.م'  },
  MDL: { name: 'Moldovan Leu',                 symbol: 'L'    },
  MGA: { name: 'Malagasy Ariary',              symbol: 'Ar'   },
  MKD: { name: 'Macedonian Denar',             symbol: 'ден'  },
  MMK: { name: 'Myanmar Kyat',                 symbol: 'K'    },
  MNT: { name: 'Mongolian Tugrik',             symbol: '₮'    },
  MOP: { name: 'Macanese Pataca',              symbol: 'P'    },
  MRU: { name: 'Mauritanian Ouguiya',          symbol: 'UM'   },
  MUR: { name: 'Mauritian Rupee',              symbol: '₨'    },
  MVR: { name: 'Maldivian Rufiyaa',            symbol: 'Rf'   },
  MWK: { name: 'Malawian Kwacha',              symbol: 'MK'   },
  MXN: { name: 'Mexican Peso',                 symbol: '$'    },
  MYR: { name: 'Malaysian Ringgit',            symbol: 'RM'   },
  MZN: { name: 'Mozambican Metical',           symbol: 'MT'   },
  NAD: { name: 'Namibian Dollar',              symbol: 'N$'   },
  NGN: { name: 'Nigerian Naira',               symbol: '₦'    },
  NIO: { name: 'Nicaraguan Córdoba',           symbol: 'C$'   },
  NOK: { name: 'Norwegian Krone',              symbol: 'kr'   },
  NPR: { name: 'Nepalese Rupee',               symbol: '₨'    },
  NZD: { name: 'New Zealand Dollar',           symbol: 'NZ$'  },
  OMR: { name: 'Omani Rial',                   symbol: 'ر.ع'  },
  PAB: { name: 'Panamanian Balboa',            symbol: 'B/.'  },
  PEN: { name: 'Peruvian Sol',                 symbol: 'S/.'  },
  PGK: { name: 'Papua New Guinean Kina',       symbol: 'K'    },
  PHP: { name: 'Philippine Peso',              symbol: '₱'    },
  PKR: { name: 'Pakistani Rupee',              symbol: '₨'    },
  PLN: { name: 'Polish Złoty',                 symbol: 'zł'   },
  PYG: { name: 'Paraguayan Guarani',           symbol: '₲'    },
  QAR: { name: 'Qatari Riyal',                 symbol: 'ر.ق'  },
  RON: { name: 'Romanian Leu',                 symbol: 'lei'  },
  RSD: { name: 'Serbian Dinar',                symbol: 'din'  },
  RUB: { name: 'Russian Ruble',                symbol: '₽'    },
  RWF: { name: 'Rwandan Franc',                symbol: 'Fr'   },
  SAR: { name: 'Saudi Riyal',                  symbol: '﷼'    },
  SBD: { name: 'Solomon Islands Dollar',       symbol: 'SI$'  },
  SCR: { name: 'Seychellois Rupee',            symbol: '₨'    },
  SDG: { name: 'Sudanese Pound',               symbol: 'ج.س.' },
  SEK: { name: 'Swedish Krona',                symbol: 'kr'   },
  SGD: { name: 'Singapore Dollar',             symbol: 'S$'   },
  SHP: { name: 'Saint Helena Pound',           symbol: '£'    },
  SLE: { name: 'Sierra Leonean Leone',         symbol: 'Le'   },
  SOS: { name: 'Somali Shilling',              symbol: 'Sh'   },
  SRD: { name: 'Surinamese Dollar',            symbol: '$'    },
  SSP: { name: 'South Sudanese Pound',         symbol: '£'    },
  STN: { name: 'São Tomé and Príncipe Dobra',  symbol: 'Db'   },
  SYP: { name: 'Syrian Pound',                 symbol: '£'    },
  SZL: { name: 'Swazi Lilangeni',              symbol: 'L'    },
  THB: { name: 'Thai Baht',                    symbol: '฿'    },
  TJS: { name: 'Tajikistani Somoni',           symbol: 'SM'   },
  TMT: { name: 'Turkmenistani Manat',          symbol: 'T'    },
  TND: { name: 'Tunisian Dinar',               symbol: 'DT'   },
  TOP: { name: "Tongan Paʻanga",          symbol: 'T$'   },
  TRY: { name: 'Turkish Lira',                 symbol: '₺'    },
  TTD: { name: 'Trinidad and Tobago Dollar',   symbol: 'TT$'  },
  TWD: { name: 'Taiwan Dollar',                symbol: 'NT$'  },
  TZS: { name: 'Tanzanian Shilling',           symbol: 'Sh'   },
  UAH: { name: 'Ukrainian Hryvnia',            symbol: '₴'    },
  UGX: { name: 'Ugandan Shilling',             symbol: 'Sh'   },
  USD: { name: 'US Dollar',                    symbol: '$'    },
  UYU: { name: 'Uruguayan Peso',               symbol: '$U'   },
  UZS: { name: 'Uzbekistan Som',               symbol: 'лв'   },
  VES: { name: 'Venezuelan Bolívar',           symbol: 'Bs.S' },
  VND: { name: 'Vietnamese Dong',              symbol: '₫'    },
  VUV: { name: 'Vanuatu Vatu',                 symbol: 'VT'   },
  WST: { name: 'Samoan Tala',                  symbol: 'T'    },
  XAF: { name: 'CFA Franc BEAC',               symbol: 'Fr'   },
  XCD: { name: 'East Caribbean Dollar',        symbol: 'EC$'  },
  XOF: { name: 'CFA Franc BCEAO',              symbol: 'Fr'   },
  XPF: { name: 'CFP Franc',                    symbol: 'Fr'   },
  YER: { name: 'Yemeni Rial',                  symbol: '﷼'    },
  ZAR: { name: 'South African Rand',           symbol: 'R'    },
  ZMW: { name: 'Zambian Kwacha',               symbol: 'ZK'   },
  ZWL: { name: 'Zimbabwean Dollar',            symbol: 'Z$'   },
}

/** Currencies shown at the top of the dropdown, before the full alphabetical list. */
export const TOP_CURRENCIES = ['USD', 'EUR', 'GBP', 'CHF', 'AED', 'AUD', 'CAD']

export function currencyName(code: string): string {
  return CURRENCIES[code]?.name ?? code
}

export function currencySymbol(code: string): string {
  return CURRENCIES[code]?.symbol ?? code
}

/** All known currency codes, sorted alphabetically. */
export const ALL_CURRENCIES = Object.keys(CURRENCIES).sort()

/** Currencies supported by the Frankfurter (ECB) provider. */
export const FRANKFURTER_CURRENCIES = new Set([
  'AUD', 'BRL', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'EUR', 'GBP', 'HKD',
  'HUF', 'IDR', 'ILS', 'INR', 'ISK', 'JPY', 'KRW', 'MXN', 'MYR', 'NOK',
  'NZD', 'PHP', 'PLN', 'RON', 'SEK', 'SGD', 'THB', 'TRY', 'USD', 'ZAR',
])

/** Returns the sorted list of currency codes available for a given rate provider. */
export function getProviderCurrencies(provider: string): string[] {
  if (provider === 'frankfurter') {
    return [...FRANKFURTER_CURRENCIES].sort()
  }
  return ALL_CURRENCIES
}
