ALTER TABLE "SystemEventsConfig" ADD COLUMN IF NOT EXISTS "showBookButton" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "OrgEventsConfig"    ADD COLUMN IF NOT EXISTS "showBookButton" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "SystemAmadeusConfig" ADD COLUMN IF NOT EXISTS "showBookButton" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "OrgAmadeusConfig"   ADD COLUMN IF NOT EXISTS "showBookButton" BOOLEAN NOT NULL DEFAULT true;
